# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3071da39e9937e656fa03f78ce4046dec4b5993944037a90d9c9b369618c78c2044585f97d40cdf49e3594bbb9756725b9cefdab7489634b44388e57c5f95d71

test:
  secret_key_base: 5de1abe781e0504c1676489c333dd883775862a56f59064c8e7d508ec0bd34391344c18f517bd7ba533d76b159127f57c28140c56c37d89cc3e8dec9ca853afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
